# Generated by Django 3.0 on 2022-02-19 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20220219_2122'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='event/images'),
        ),
        migrations.AlterField(
            model_name='event',
            name='income',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='event',
            name='tags',
            field=models.CharField(blank=True, help_text='tags separated by space', max_length=255, null=True),
        ),
    ]
