# Generated by Django 3.0 on 2022-03-09 16:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_balance', models.PositiveIntegerField(default=0)),
                ('bank_account_name', models.CharField(blank=True, max_length=300, null=True)),
                ('bank_account_number', models.PositiveIntegerField(default=0)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Withdrawal',
            fields=[
                ('transaction_id', models.AutoField(primary_key=True, serialize=False)),
                ('previous_amount', models.PositiveIntegerField(default=0)),
                ('current_amount', models.PositiveIntegerField(default=0)),
                ('withdrawal_amout', models.PositiveIntegerField(default=0)),
                ('create_date', models.DateTimeField(auto_now=True)),
                ('creator', models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, related_name='creator', to='wallets.Wallet')),
            ],
        ),
    ]
