# Generated by Django 3.0 on 2022-02-19 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='ticket_number',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
